### ISSUE TITLE
Position problem when using `display: flex;`

### ISSUE THREAD

**Issue by itayganor** [VsevolodTrofimov/Ripple.js#13]
Hey!
I'm using `display: flex;` for an element, and this element has children with ripple watch on them.
It seems there's a problem with the flex displaying and the ripple position.
As you can see in my site: ****
the ripple effect seems to be a few pixels left.

Is there any solution for it? Thanks!

**Comment by VsevolodTrofimov** [comment]
I will check in ~10hrs(it's really late in my timezone now) 

Please make sure the you use the latest (0.4.2) version, as the was rtl bug pointed out in #12

**Comment by v-trof** [comment]
Hmm, this seems to be an issue with you body clientRect or margins (as there is no bug when scrollbar is present)
So can you please plugin in this version of ripple.js file (this will have Position debug console.logs and is not minified so it will be easier to see what exacly has gone wrong)
[ripple.zip](https://github.com/VsevolodTrofimov/Ripple.js/files/1150198/ripple.zip)

**Comment by itayganor** [comment]
I have updated it now.

**Comment by v-trof** [comment]
Ok, I've got it:
For some odd reason (I'm not sure if it's due to ripple or your website) at the very moment ripple gets created(but not when it's animating so it shouldn't be a ripple JS bug)
Scrollbar flashes in and button&input move a bit to the side, that's why ripple gets their positions wrong
![screenshot_8](https://user-images.githubusercontent.com/10118898/28239641-bdb87bec-6979-11e7-9da3-9bce6b36a5e4.png)
![screenshot_9](https://user-images.githubusercontent.com/10118898/28239642-bdba1682-6979-11e7-8738-21a8b99061ae.png)

**Comment by v-trof** [comment]
My suggestion would be
Preset `top: 0px` for `.ripple` so that browsers wouldn't caculate layout change for it
I will have it fixed this way in 0.4.3
